bb_config:
  name: MLPBackbone
  hidden_size: 512
  n_layers: 5

cn_config:
  name: MLPConditioner
  hidden_size: 256
  latent_dim: 128

diff_config:
  name: MovingAvgDiffusion
  freq_kw: 
    frequency: on
    real_imag: on
  seq_length: 288
  noise_kw: 
    name: linear
    min_beta: 1.0e-4
    max_beta: 2.0e-2
  norm: on
  fit_on_diff: on

train_config:
  epochs: 150
  lr: 2.0e-4
  early_stop: 5
  val_step: 1