bb_config:
  name: DiT
  # name: MLPBackbone
  d_model: 128
  # d_mlp: 1024
  # hidden_size: 512
  n_layers: 8
  patch_size: 8
  num_heads: 4
  # dropout: 0.1
  # obs_seq_length: 96

cn_config:
  name: MLPConditioner
  hidden_size: 256
  latent_dim: 128

diff_config:
  name: MADFreq
  noise_schedule: freqresp
  norm: on
  pred_diff: on

train_config:
  epochs: 100
  lr: 2.0e-4
  early_stop: 5
  val_step: 1
