bb_config:
  name: DiT
  # name: MLPBackbone
  d_model: 128
  # d_mlp: 1024
  # hidden_size: 512
  n_layers: 4
  patch_size: 7
  # num_heads: 8
  # dropout: 0.1
  attn_drop: 0.1
  proj_drop: 0.1
  freq: on
  # bias: False
  # obs_seq_length: 96

cn_config:
  # name: MLPConditioner
  name: RMLPConditioner
  hidden_size: 512
  latent_dim: 128

diff_config:
  name: MADFreq
  noise_schedule: freqresp
  norm: off
  pred_diff: on

train_config:
  epochs: 100
  lr: 2.0e-4
  early_stop: 5
  val_step: 1
  alpha: 1.0e-9
