bb_config:
  name: RMLPBackbone
  # input_seq_length: 96
  # name: MLPBackbone
  d_model: 128
  d_mlp: 512
  # hidden_size: 128
  n_layers: 3
  # patch_size: 8
  # num_heads: 8
  dropout: 0.3
  # bias: False
  # obs_seq_length: 96

cn_config:
  name: RMLPStatsConditioner
  # name: IdentityConditioner
  hidden_size: 256
  latent_dim: 128

diff_config:
  name: MAD
  noise_schedule: freqresp
  norm: on
  pred_diff: off
  freq: on

train_config:
  epochs: 10
  lr: 1.0e-3
  early_stop: 5
  val_step: 1
  alpha: 0.0
