bb_config:
  name: MLPBackbone
  d_model: 128
  # patch_size: 8
  # num_heads: 4
  d_mlp: 512 # original 512
  n_layers: 3 # original 3
  dropout: 0.1
  cond_dropout_prob: 0.0
  norm: on
  freq_denoise: off

diff_config:
  name: MADTC
  noise_schedule: std
  norm: on
  pred_diff: on
  T: 100

train_config:
  epochs: 100
  lr: 2.0e-4
  early_stop: 5
  val_step: 1
  alpha: 1.0e-9
