bb_config:
  name: MLPStatsBackbone
  input_seq_length: 96
  # name: MLPBackbone
  d_model: 128
  d_mlp: 1024
  # hidden_size: 128
  n_layers: 3
  # patch_size: 8
  # num_heads: 8
  dropout: 0.1
  # bias: False
  # obs_seq_length: 96

cn_config:
  name: MLPStatsConditioner
  # name: IdentityConditioner
  hidden_size: 512
  latent_dim: 128

diff_config:
  name: MADTime
  noise_schedule: std
  norm: on
  pred_diff: off

train_config:
  epochs: 100
  lr: 2.0e-4
  early_stop: 5
  val_step: 1
  alpha: 1.0e-9
