bb_config:
  name: MLPBackbone
  d_model: 128
  d_mlp: 512 # original 512
  n_layers: 3 # original 3
  dropout: 0.1

cn_config:
  name: MLPStatsConditioner
  hidden_size: 256
  latent_dim: 128
  norm: on

diff_config:
  name: MAD
  noise_schedule: std
  norm: on
  pred_diff: off
  freq: off
  factor_only: off
  stride_equal_to_kernel_size: on

train_config:
  epochs: 100
  lr: 2.0e-4
  early_stop: 5
  val_step: 1
  alpha: 1.0e-9
