data: ETTm2
root_path: /home/user/workspaces/THU-timeseries
# root_path: /mnt/ExtraDisk/wcx/research/THU-timeseries
data_path: ETT-small/ETTm2.csv
features: S
target: OT
num_workers: 1
seq_len: 96
pred_len: 96
label_len: 0
batch_size: 128
condition: Null
kernel_size: 8