data: ETTm1
root_path: /home/user/data/THU-timeseries
# root_path: /mnt/ExtraDisk/wcx/research/THU-timeseries
data_path: ETT-small/ETTm1.csv
features: S
target: OT
num_workers: 1
seq_len: 96
pred_len: 96
label_len: 0
batch_size: 128