data: custom
root_path: /home/user/data/THU-timeseries
# root_path: /mnt/ExtraDisk/wcx/research/THU-timeseries
data_path: MFRED/MFRED.csv
features: S
target: OT
num_workers: 1
seq_len: 576
pred_len: 576
label_len: 0
batch_size: 128
condition: Null
kernel_size: 8