data: custom
root_path: /mnt/ExtraDisk/wcx/research/FrequencyDiffusion
data_path: dataset/MFRED_clean.csv
features: S
target: value
num_workers: 1
seq_len: 288
pred_len: 288
label_len: 0
batch_size: 128