data: custom
root_path: /home/user/data/THU-timeseries
# root_path: /mnt/ExtraDisk/wcx/research/THU-timeseries
data_path: weather/weather.csv
features: S
target: T (degC)
num_workers: 1
seq_len: 96
pred_len: 96
label_len: 0
batch_size: 128