bb_config:
  name: MLPBackbone
  hidden_size: 512
  n_layers: 5

cn_config:
  name: MLPConditioner
  hidden_size: 256
  latent_dim: 128

diff_config:
  name: MADTime
  noise_schedule: empirical
  norm: off
  pred_diff: off

train_config:
  epochs: 150
  lr: 2.0e-4
  early_stop: 5
  val_step: 1
