data_config:
  target: value
  n_in: 288
  n_out: 288
  shift: 0
  col_in: 
    - value
  col_out: 
    - t2m
  batch_size: 128
  scale: on

backbone: MLPBackbone
bb_config:
  hidden_size: 128
  n_layers: 10

conditioner: MLPConditioner
cn_config:
  hidden_size: 256
  latent_dim: 128

diffusion: MovingAvgDiffusion
diff_config:
  freq_kw: 
    frequency: off
  seq_length: 288
  noise_kw: 
      min_beta: 1.0e-4
      max_beta: 2.0e-2
  # fast_sample: on
  only_factor_step: True

train_config:
  epochs: 150
  lr: 2.0e-4
  early_stop: 5