data_config:
  target: power
  n_in: 288
  n_out: 288
  shift: 0
  col_in: 
    - power
  col_out: 
    - u100
    - v100
  batch_size: 128

backbone: MLPBackbone
bb_config:
  hidden_size: 256
  # latent_dim: 64
  n_layers: 10

conditioner: MLPConditioner
cn_config:
  hidden_size: 256
  latent_dim: 256

diffusion: MovingAvgDiffusion
diff_config:
  freq_kw: 
    frequency: on
    stereographic: off
  seq_length: 400
  # T: 100
  # min_beta: 1.0e-4
  # max_beta: 2.0e-2

train_config:
  epochs: 300
  lr: 1.0e-4