data_config:
  target: power
  n_in: 288
  n_out: 288
  shift: 0
  col_in: 
    - power
  col_out: 
    - u100
    - v100
  batch_size: 128
  scale: on

backbone: UNetBackbone
bb_config:
  hidden_size: 32

conditioner: MLPConditioner
cn_config:
  hidden_size: 256
  latent_dim: 128

diffusion: MovingAvgDiffusion
diff_config:
  freq_kw: 
    frequency: off
  seq_length: 288


train_config:
  epochs: 150
  lr: 2.0e-4
  early_stop: 5