data_config:
  target: power
  n_in: 288
  n_out: 288
  shift: 0
  col_in: 
    - power
  col_out: 
    - u100
    - v100
  batch_size: 128
  scale: on

backbone: ResNetBackbone
# backbone: MLPBackbone
bb_config:
  hidden_size: 128
  n_layers: 5


conditioner: MLPConditioner
cn_config:
  hidden_size: 128
  latent_dim: 128


diffusion: MovingAvgDiffusion
diff_config:
  freq_kw: 
    frequency: off
    stereographic: off
  seq_length: 288


train_config:
  epochs: 300
  lr: 1.0e-4