backbone: MLPBackbone
bb_config:
  hidden_size: 256
  # latent_dim: 64
  n_layers: 3

conditioner: MLPConditioner
cn_config:
  hidden_size: 256
  latent_dim: 256


diffusion: MovingAvgDiffusion
diff_config:
  freq_kw: 
    frequency: on
    stereographic: off
  seq_length: 400
  # T: 100
  # min_beta: 1.0e-4
  # max_beta: 2.0e-2

train_config:
  epochs: 300
  lr: 1.0e-4